markdown: kramdown
description: Making sense of a fast-evolving world
title: SCATTA
url: "http://tri47.github.io/"
exclude: [README.md, .gitignore, Gemfile, Gemfile.lock]
theme: minima
social_links:
  github: tri47
  linkedin: tri-q-nguyen
  rss: rss
author:
  name: Tri Nguyen
  email: jnqtri@gmail.com
minima:
  skin: dark
google_analytics: UA-167295992-1
plugins:
  - jekyll-feed
excerpt_separator: "<!--break-->"


