markdown: kramdown
description: Making sense of an entangled world
title: Tri Nguyen
url: "http://tri47.github.io/"
exclude: [README.md, .gitignore, Gemfile, Gemfile.lock]
theme: minima
social_links:
  github: tri47
  linkedin: tri-q-nguyen
author:
  name: Tri Nguyen
  email: jnqtri@gmail.com
minima:
  skin: dark
